#!/bin/bash

pushd $(dirname $0) > /dev/null

rm -rf ./dist/*

find ./ -iname "*.md" -type f -exec bash -c 'echo -e "\x1B[1mConverting ${0}\x1B[0m" && mkdir -p $(dirname "dist/${0%.md}.html") && pandoc --css "/global.css" --highlight-style "./code.theme" -s "${0}" -o "dist/${0%.md}.html"' {} \;

find ./ \
  -not -path './dist/*' \
  -not -name "*.md" \
  -not -name "build" \
  -not -name "watch" \
  -not -name "code.theme" \
  -not -name ".gitignore" \
  -not -name ".git" \
  -not -name ".github" \
  -type f \
  -exec sh -c 'mkdir -p $(dirname "dist/${0}") && cp "${0}" "dist/${0%.md}"' {} \;

popd > /dev/null
