#!/bin/bash

tempfile=$(mktemp)

./build

while true
do
       touch $tempfile
       sleep 0.5
       if find . -not -path "./dist*" -cnewer "$tempfile" -print0 | grep -qz .; then
        echo "Updated!"
        ./build
       fi
done

